### ISSUE TITLE
Fails on adding route

### ISSUE THREAD

**Issue by woop** [rimusz/gke-internal-lb#4]
Firstly, thanks for creating the script. Exactly what I was looking for. I'm getting an error on the final step though.

When I run:
```
gcloud compute routes create ip-$VM_FULL_NAME \
         --next-hop-instance $VM_FULL_NAME \
            --next-hop-instance-zone $ZONE \
                --destination-range $STATIC_IP/32
```
The output is:
```
ERROR: (gcloud.compute.routes.create) Some requests did not succeed:
 - Invalid value for field 'resource.destRange': '10.148.252.10/32'. 10.148.252.10/32 hides the reserved address space for network (10.148.0.0/16).
```
I've confirmed that the variables exist and that they are accurate.

Any ideas?

**Comment by rimusz** [comment]
must be `gcloud` commands been changed, will look to it when I have some spare time

**Comment by woop** [comment]
Great, thanks!

**Comment by woop** [comment]
Resolved. Can't add a /32 route inside of an existing network.
